language: node_js
node_js:
  - "stable"
services:
  - docker
cache:
  directories:
    - node_modules
    - dist
install:
  - yarn install
  - cd ./website/
  - yarn install
  - cd ../
script:
  - yarn build
  - cd ./website/
  - yarn build
  - cd ../
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
